package presentacion;



import javax.swing.JOptionPane;
import javax.swing.ProgressMonitor;

import configuracion.Configuracion;
import configuracion.Genotipo_enum;
import configuracion.Mutacion_enum;
import configuracion.Reproduccion_enum;
import configuracion.Seleccion_enum;

/**
 *
 * @author carlo
 */
public class PanelInfo extends javax.swing.JPanel {
	public PanelInfo() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jTextFieldPoblacion = new javax.swing.JTextField();
		jLabelPoblacion = new javax.swing.JLabel();
		jLabelGeneraciones = new javax.swing.JLabel();
		jTextFieldGeneraciones = new javax.swing.JTextField();
		jLabelSeleccion = new javax.swing.JLabel();
		jComboBoxSeleccion = new javax.swing.JComboBox<>();
		jComboBoxCruce = new javax.swing.JComboBox<>();
		jLabelCruce = new javax.swing.JLabel();
		jLabelCruceporcentaje = new javax.swing.JLabel();
		jTextFieldCruceporcentaje = new javax.swing.JTextField();
		jLabelProbMutacion = new javax.swing.JLabel();
		jTextFieldProbMutacion = new javax.swing.JTextField();
		jTextFieldElite = new javax.swing.JTextField();
		jLabelElite = new javax.swing.JLabel();
		jScrollPane4 = new javax.swing.JScrollPane();
		jTextArea4 = new javax.swing.JTextArea();
		jButtonRun = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jTextFieldProfundidad = new javax.swing.JTextField();
		jComboBoxMutacion = new javax.swing.JComboBox<>();
		jPanel1 = new javax.swing.JPanel();
		jLabelFunciones = new javax.swing.JLabel();
		jCheckBoxSuma = new javax.swing.JCheckBox();
		jCheckBoxResta = new javax.swing.JCheckBox();
		jCheckBoxRaiz = new javax.swing.JCheckBox();
		jCheckBoxMultiplicacion = new javax.swing.JCheckBox();
		jCheckBoxDivision = new javax.swing.JCheckBox();
		jCheckBoxRaiz1 = new javax.swing.JCheckBox();

		setAutoscrolls(true);
		setPreferredSize(new java.awt.Dimension(400, 200));

		jTextFieldPoblacion.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
		jTextFieldPoblacion.setToolTipText("Introduce el tamaño de la poblacion (valor entero)");
		jTextFieldPoblacion.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldPoblacionActionPerformed(evt);
			}
		});

		jLabelPoblacion.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
		jLabelPoblacion.setText("Tamaño de la poblacion");

		jLabelGeneraciones.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
		jLabelGeneraciones.setText("Numero de generaciones");

		jTextFieldGeneraciones.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
		jTextFieldGeneraciones.setToolTipText("Introduce el numero de generaciones (valor entero)");
		jTextFieldGeneraciones.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldGeneracionesActionPerformed(evt);
			}
		});

		jLabelSeleccion.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
		jLabelSeleccion.setText("Seleccion");

		jComboBoxSeleccion.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
		jComboBoxSeleccion.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Ruleta", "Estocastica", "Truncamiento", "Torneo Deterministico",
						"Torneo Probabilistico"}));
		jComboBoxSeleccion.setToolTipText("Elige un método de seleccion");
		jComboBoxSeleccion.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBoxSeleccionActionPerformed(evt);
			}
		});

		jComboBoxCruce.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
		jComboBoxCruce.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cruce arbol"}));
		jComboBoxCruce.setToolTipText("Selecciona un mecanismo de cruce");
		jComboBoxCruce.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		jComboBoxCruce.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBoxCruceActionPerformed(evt);
			}
		});

		jLabelCruce.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
		jLabelCruce.setText("Cruce");

		jLabelCruceporcentaje.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
		jLabelCruceporcentaje.setText("Cruce %");

		jTextFieldCruceporcentaje.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
		jTextFieldCruceporcentaje.setToolTipText("Selecciona un porcentaje de cruce");
		jTextFieldCruceporcentaje.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldCruceporcentajeActionPerformed(evt);
			}
		});

		jLabelProbMutacion.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
		jLabelProbMutacion.setText("Prob Mutacion");

		jTextFieldProbMutacion.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
		jTextFieldProbMutacion.setToolTipText("Selecciona un porcentaje de cruce");
		jTextFieldProbMutacion.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldProbMutacionActionPerformed(evt);
			}
		});

		jTextFieldElite.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
		jTextFieldElite.setToolTipText("Selecciona un porcentaje de cruce");
		jTextFieldElite.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldProbMutacion1ActionPerformed(evt);
			}
		});

		jLabelElite.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
		jLabelElite.setText("Elite");

		jTextArea4.setEditable(false);
		jTextArea4.setBackground(new java.awt.Color(239, 234, 234));
		jTextArea4.setColumns(20);
		jTextArea4.setRows(5);
		jTextArea4.setAutoscrolls(false);
		jScrollPane4.setViewportView(jTextArea4);

		jButtonRun.setText("Run");
		jButtonRun.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonRunActionPerformed(evt);
			}
		});

		jLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
		jLabel1.setText("Profundidad maxima");

		jComboBoxMutacion.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
		jComboBoxMutacion.setModel(new javax.swing.DefaultComboBoxModel<>(
				new String[] { "De arbol", "Funcional simple", "Terminal simple" }));
		jComboBoxMutacion.setToolTipText("Selecciona un mecanismo de cruce");
		jComboBoxMutacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		jComboBoxMutacion.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBoxMutacionActionPerformed(evt);
			}
		});

		jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

		jLabelFunciones.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
		jLabelFunciones.setText("Funciones");

		jCheckBoxSuma.setText("+");
		jCheckBoxSuma.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBoxSumaActionPerformed(evt);
			}
		});

		jCheckBoxResta.setText("-");
		jCheckBoxResta.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBoxRestaActionPerformed(evt);
			}
		});

		jCheckBoxRaiz.setText("sqrt");
		jCheckBoxRaiz.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBoxRaizActionPerformed(evt);
			}
		});

		jCheckBoxMultiplicacion.setText("*");
		jCheckBoxMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBoxMultiplicacionActionPerformed(evt);
			}
		});

		jCheckBoxDivision.setText("/");
		jCheckBoxDivision.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBoxDivisionActionPerformed(evt);
			}
		});

		jCheckBoxRaiz1.setText("log");
		jCheckBoxRaiz1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBoxRaiz1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabelFunciones)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jCheckBoxSuma).addComponent(jCheckBoxMultiplicacion))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jCheckBoxResta).addComponent(jCheckBoxDivision))
								.addGap(104, 104, 104)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jCheckBoxRaiz1).addComponent(jCheckBoxRaiz))
								.addGap(23, 23, 23)))));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jLabelFunciones)
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jCheckBoxSuma).addComponent(jCheckBoxResta).addComponent(jCheckBoxRaiz))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jCheckBoxMultiplicacion).addComponent(jCheckBoxDivision).addComponent(
										jCheckBoxRaiz1))
						.addGap(27, 27, 27)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
						.createSequentialGroup().addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
										javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup().addContainerGap().addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(layout.createSequentialGroup().addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout
																.createSequentialGroup()
																.addComponent(jTextFieldCruceporcentaje,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 45,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(jComboBoxCruce,
																		0, javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE))
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addGroup(layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																		.addComponent(jLabelPoblacion)
																		.addComponent(jLabelGeneraciones,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(jTextFieldGeneraciones)
																		.addComponent(jTextFieldPoblacion))
																.addGroup(layout.createSequentialGroup()
																		.addComponent(jLabelCruceporcentaje)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(jLabelCruce))))
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100,
																Short.MAX_VALUE)
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING,
																		false)
																.addComponent(jTextFieldProfundidad,
																		javax.swing.GroupLayout.Alignment.TRAILING,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 140,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(layout.createSequentialGroup()
																						.addComponent(jLabelSeleccion)
																						.addGap(41, 41, 41)
																						.addComponent(jLabelElite))
																				.addGroup(layout.createSequentialGroup()
																						.addComponent(
																								jComboBoxSeleccion,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								72,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(jTextFieldElite,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								62,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addComponent(jLabel1))
																.addComponent(jLabelProbMutacion)
																.addGroup(layout.createSequentialGroup()
																		.addComponent(jTextFieldProbMutacion,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				42,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(jComboBoxMutacion,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				88,
																				javax.swing.GroupLayout.PREFERRED_SIZE))))))
								.addGroup(layout.createSequentialGroup().addGap(173, 173, 173).addComponent(jButtonRun)
										.addGap(0, 0, Short.MAX_VALUE))
								.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jPanel1,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)))
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jLabelPoblacion).addComponent(jLabelSeleccion).addComponent(jLabelElite))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jTextFieldPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jComboBoxSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jTextFieldElite, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jLabelGeneraciones).addComponent(jLabel1))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jTextFieldGeneraciones, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jTextFieldProfundidad, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jLabelCruceporcentaje).addComponent(jLabelCruce).addComponent(jLabelProbMutacion))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jTextFieldCruceporcentaje, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jComboBoxCruce, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jTextFieldProbMutacion, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jComboBoxMutacion, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 185,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(18, 18, 18).addComponent(jButtonRun)
				.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		cosasPorDefecto();
	}// </editor-fold>

	private void cosasPorDefecto() {

		this.jTextFieldPoblacion.setText("300");
		this.jTextFieldCruceporcentaje.setText("60");
		this.jTextFieldGeneraciones.setText("200");
		this.jTextFieldProbMutacion.setText("8");
		this.jTextFieldElite.setText("5");

		this.jTextArea4.setLineWrap(true);
		this.jTextArea4.setWrapStyleWord(true);
	}

	private void jTextFieldPoblacionActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextFieldGeneracionesActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jComboBoxSeleccionActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jComboBoxCruceActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextFieldCruceporcentajeActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextFieldProbMutacionActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextFieldProbMutacion1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jComboBoxMutacionActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBoxSumaActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBoxRestaActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBoxRaizActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBoxMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBoxDivisionActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBoxRaiz1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButtonRunActionPerformed(java.awt.event.ActionEvent evt) {
		if (this.jTextFieldPoblacion.getText().isEmpty() || jTextFieldGeneraciones.getText().isEmpty()
				|| jTextFieldCruceporcentaje.getText().isEmpty() || this.jTextFieldProbMutacion.getText().isEmpty()) {
			JOptionPane.showMessageDialog(null, "Error: Faltan datos", "error", JOptionPane.ERROR_MESSAGE);
		} else {
			// String tipo = (String) this.jComboBoxTipo.getSelectedItem();
			// this.tipo = tipo;
			int tamano_poblacion = Integer.parseInt(this.jTextFieldPoblacion.getText());
			int num_generaciones = Integer.parseInt(this.jTextFieldGeneraciones.getText());
			String seleccion = (String) this.jComboBoxSeleccion.getSelectedItem();
			String cruce = (String) this.jComboBoxCruce.getSelectedItem();
			String mutacion = (String) this.jComboBoxMutacion.getSelectedItem();
			double cruceporcentaje = Double.parseDouble(this.jTextFieldCruceporcentaje.getText());
			double prob_mutacion = Double.parseDouble(this.jTextFieldProbMutacion.getText());
			int elite = Integer.parseInt(this.jTextFieldElite.getText());
			Seleccion_enum s = getSeleccion(seleccion);
			Reproduccion_enum r = getReproduccion(cruce);
			Genotipo_enum g = Genotipo_enum.ALFABETO;
			Mutacion_enum m = getMutacion(mutacion);

			Configuracion c = new Configuracion(true, num_generaciones, prob_mutacion, r, m, s, g, cruceporcentaje,
					tamano_poblacion, elite, "", Integer.parseInt(jTextFieldProfundidad.getText()));

			// jProgressBar1 = new JProgressBar(0, task.getLengthOfTask());
			// jProgressBar1.setValue(0);
			// jProgressBar1.setStringPainted(true);

			Controlador controlador = new Controlador();
			// System.out.println("tamaño de la poblacion" + tamano_poblacion);
			controlador.execute(c);
		}
	}

	private Seleccion_enum getSeleccion(String s) {
		if (s.equalsIgnoreCase("Ruleta"))
			return Seleccion_enum.Ruleta;
		else if (s.equalsIgnoreCase("Estocastica"))
			return Seleccion_enum.Estocastica;
		else if (s.equalsIgnoreCase("Truncamiento"))
			return Seleccion_enum.Truncamiento;
		else if (s.equalsIgnoreCase("Torneo Deterministico"))
			return Seleccion_enum.Torneo_Deterministico;
		else if (s.equalsIgnoreCase("Torneo Probabilistico"))
			return Seleccion_enum.Torneo_Probabilistico;
		else
			return null;
	}

	private Reproduccion_enum getReproduccion(String s) {
		return Reproduccion_enum.CRUCE_ARBOL;
	}

	private Mutacion_enum getMutacion(String s) {
		switch (s) {
		case "Mutacion de arbol":
			return Mutacion_enum.MUTACION_DE_ARBOL;
		case "Mutacion funcional simple":
			return Mutacion_enum.MUTACION_FUNCIONAL_SIMPLE;
		case "Mutacion terminal simple":
			return Mutacion_enum.MUTACION_TERMINAL_SIMPLE;

		default:
			return null;
		}

	}

	// Variables declaration - do not modify
	private javax.swing.JButton jButtonRun;
	private javax.swing.JCheckBox jCheckBoxDivision;
	private javax.swing.JCheckBox jCheckBoxMultiplicacion;
	private javax.swing.JCheckBox jCheckBoxRaiz;
	private javax.swing.JCheckBox jCheckBoxRaiz1;
	private javax.swing.JCheckBox jCheckBoxResta;
	private javax.swing.JCheckBox jCheckBoxSuma;
	private javax.swing.JComboBox<String> jComboBoxCruce;
	private javax.swing.JComboBox<String> jComboBoxMutacion;
	private javax.swing.JComboBox<String> jComboBoxSeleccion;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabelCruce;
	private javax.swing.JLabel jLabelCruceporcentaje;
	private javax.swing.JLabel jLabelElite;
	private javax.swing.JLabel jLabelFunciones;
	private javax.swing.JLabel jLabelGeneraciones;
	private javax.swing.JLabel jLabelPoblacion;
	private javax.swing.JLabel jLabelProbMutacion;
	private javax.swing.JLabel jLabelSeleccion;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JTextArea jTextArea4;
	private javax.swing.JTextField jTextFieldCruceporcentaje;
	private javax.swing.JTextField jTextFieldGeneraciones;
	private javax.swing.JTextField jTextFieldPoblacion;
	private javax.swing.JTextField jTextFieldProbMutacion;
	private javax.swing.JTextField jTextFieldElite;
	private javax.swing.JTextField jTextFieldProfundidad;
	// End of variables declaration
	public void setTexto(String mensaje, String estadisticas) {
		jTextArea4.setText(mensaje + " " + estadisticas);
		
	}
}
